name: json_guard
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/abrahammurciano/json_guard
environment:
  sdk: ^3.8.1
dependencies:
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
